### ISSUE TITLE
Make all clickable elements change mouse pointer

### ISSUE THREAD

**Issue by solashirai** [CS3733-TeamAlpha/Project#108]
This should be one of the last issues to fix, but we need to make sure all clickable things properly change the mouse pointer to improve clarity.

**Comment by C7C8** [comment]
Looked into it very briefly, the only way i can see of doing it so far is to set mouesover handlers for every clickable imageview. It can be done, it's just a LOT of repetitive code.

**Comment by solashirai** [comment]
we just need to use CSS and make sure that any newly added element (mostly buttons) has the appropriate class/ID set. it's not even that much work. i just set this as an issue to make sure we check that everything is styled correctly at the end.

**Comment by C7C8** [comment]
If we can do it in CSS and not java, let's do it in CSS. CSS is magical, I guess... my bad

**Comment by solashirai** [comment]
Yeah, css is magical (except when it decides to be a difficult bitch, which sometimes happens). 

Don't worry about this issue much, since nearly everything already does change mouse pointer as intended
