### ISSUE TITLE
Depth first search teleports through elevators

### ISSUE THREAD

**Issue by solashirai** [CS3733-TeamAlpha/Project#109]
Depth first search option testing form 3rd floor faulkner kiosk jumps from the elevators in the lower half of the map (on the 3rd floor) to the elevators in the upper half of the map (on the 1st floor). not sure if this is entirely a bug by pathfinding or the map controller

**Comment by solashirai** [comment]
Going from the 3rd floor kiosk takes you on a path all the way up to the 7th floor and going around to weird places before going back down to the 1st floor. 

I suppose depth first is working as intended, but it looks weird because we only are showing the kiosk floor and target floor.

**Comment by C7C8** [comment]
It's a feature, not a bug.

**Comment by C7C8** [comment]
Depth First Search will be removed.

**Comment by C7C8** [comment]
![dfs](https://cdn.meme.am/cache/instances/folder941/500x/75883941.jpg)
