### ISSUE TITLE
Drag and drop no longer functioning correctly on `develop`

### ISSUE THREAD

**Issue by elfenari** [CS3733-TeamAlpha/Project#35]
drag and drop is giving null pointer exceptions, possibly to do with the merge of `feature-UIRefactor`

**Comment by solashirai** [comment]
yeah i had a stupid bug in there that I noticed a few minutes ago, i'll push a fix soon

**Comment by solashirai** [comment]
@elfenari Check the updated develop and let me know if the issue persist.

**Comment by elfenari** [comment]
Fixed
