### ISSUE TITLE
DatabaseController.insertNode(ConcreteNode) yields nullptr exception when given node has no data

### ISSUE THREAD

**Issue by C7C8** [CS3733-TeamAlpha/Project#7]
When a ConcreteNode with a defined data array but no actual data in it is inserted into the database, a nullptr exception is generated at data.DatabaseController.java:681.

**Comment by solashirai** [comment]
commit fixing this issue has been pushed 
Also preemptively fixed the same issue that would have occured from modifyNodeTable(concretenode).
I'll wait on you to verify and close

**Comment by C7C8** [comment]
(that commit is just me using `git cherry-pick`, by the way, it's a neat git command for bringing only certain commits into branch rather than just flat out merging things)

That looks like it did it. I'm still getting a ton of database errors, but there's no nullptr anymore. issue resolved as far as I'm concerned.
