### ISSUE TITLE
Add NodeType enum so adding a kiosk is easier

### ISSUE THREAD

**Issue by C7C8** [CS3733-TeamAlpha/Project#81]

**Comment by solashirai** [comment]
make this change just in editor tool so that we don't need to modify the database btw

**Comment by C7C8** [comment]
I'm probably just going to replace the existing text box for type with a choicebox.

**Comment by solashirai** [comment]
This was reassigned to ari but it looks like you've committed something referencing this. So should Ari still work on this or is it handled by you @Sourec ?

**Comment by C7C8** [comment]
I am working on this in a separate branch; it is heavily used in the new stairs/elevator selection system

**Comment by C7C8** [comment]
Node type enum is implemented, I'm just working on getting the choicebox working now

**Comment by C7C8** [comment]
Adding a parking lot type now too

**Comment by C7C8** [comment]
Implemented in d226e9a16874f4073bea09743234c05d776ba362
