### ISSUE TITLE
Database unit tests are disrupted by current database files

### ISSUE THREAD

**Issue by C7C8** [CS3733-TeamAlpha/Project#9]
Previously testGets, testProviderAtNode, and testInitialization unit tests were all failing... until I `rm -r` 'd (i.e. deleted) the FHAlpha directory, that is. Now they all pass, meaning that our unit tests are not quite as isolated from project state as they should be.

**Comment by solashirai** [comment]
Oh i've been incredibly stupid with how I was testing this stuff...
For this testing, I'll rewrite it in a bit to create an entirely new database in a different directory (TestFHAlpha?) and just run all the tests in there. Then at the end of the test perhaps will also remove that directory. that'll isolate tests from project, and it shouldn't be too hard to do.

**Comment by C7C8** [comment]
Resolved.... mostly
