### ISSUE TITLE
Fix useless text directions

### ISSUE THREAD

**Issue by solashirai** [CS3733-TeamAlpha/Project#97]
Some of the current text directions are very confusing/useless. A prime example is seen in any path going down the elevator from the 3rd floor kiosk. Along the long hallway, you are told you turn left towards the elevator twice in a row. 

Wherever the two exact nodes are that are causing this print, it's clear that the text directions need to be refined a little bit with regards to the "...towards the ..." kinds of prints. 
I'll assign this to myself for the time being since I don't have other issues I'm currently working on, but if someone would like to look into this problem as well let me know.

**Comment by solashirai** [comment]
Outdoors should rename all "hallway"s to "sidewalk"s

**Comment by C7C8** [comment]
Addressed in #96 ?
